# Generated by Django 5.0.14 on 2026-01-14 00:44

import django.db.models.deletion
import pix.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.CharField(default=pix.models.generate_id, max_length=20, primary_key=True, serialize=False)),
                ('ispb', models.CharField(db_index=True, max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pix_stream',
                'indexes': [models.Index(fields=['ispb', 'status'], name='pix_stream_ispb_92ca36_idx')],
            },
        ),
        migrations.CreateModel(
            name='PixMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('end_to_end_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pagador', models.JSONField()),
                ('recebedor', models.JSONField()),
                ('campo_livre', models.TextField(blank=True, default='')),
                ('tx_id', models.CharField(blank=True, default='', max_length=35)),
                ('data_hora_pagamento', models.DateTimeField()),
                ('recebedor_ispb', models.CharField(db_index=True, max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('confirmed', 'Confirmed')], db_index=True, default='pending', max_length=15)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='pix.stream')),
            ],
            options={
                'db_table': 'pix_message',
                'indexes': [models.Index(fields=['recebedor_ispb', 'status'], name='pix_message_recebed_96ca2d_idx'), models.Index(fields=['status', 'stream'], name='pix_message_status_18b0dd_idx')],
            },
        ),
    ]
